version: "3.8"

services:
  app:
    container_name: my-spring-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:

      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

  redis:
    container_name: my-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"